Setup New Base commit - f2134db
openshift-pipelines/tektoncd-results-for-konflux pull request #13
Opened 2022-10-03 19:51 UTC by adambkaplan

Set up a new branch as our default, based on the latest upstream commit.

This includes the following carry patches:

- Configuring HACBS
- Proto definitions for log forwarding/storage
- Initial implementation of log forwarding/storage

2022-10-04 10:13 UTC, avinal requested changes

2022-10-04 10:13 UTC, avinal commented on .tekton/tekton-results-api-pull-request.yaml
> +    pipelinesascode.tekton.dev/on-target-branch: "[pipelines-svc-0.1-6e05d4d]"
```suggestion
    pipelinesascode.tekton.dev/on-target-branch: "[pipeline-svc-0.1-f2134db]"
```
Update branch ref

2022-10-04 10:13 UTC, avinal commented on .tekton/tekton-results-api-push.yaml
> +    pipelinesascode.tekton.dev/on-target-branch: "[pipelines-svc-0.1-6e05d4d]"
```suggestion
    pipelinesascode.tekton.dev/on-target-branch: "[pipeline-svc-0.1-f2134db]"
```

2022-10-04 10:13 UTC, avinal commented on .tekton/tekton-results-watcher-pull-request.yaml
> +    pipelinesascode.tekton.dev/on-target-branch: "[pipelines-svc-0.1-6e05d4d]"
```suggestion
    pipelinesascode.tekton.dev/on-target-branch: "[pipeline-svc-0.1-f2134db]"
```

2022-10-04 10:13 UTC, avinal commented on .tekton/tekton-results-watcher-push.yaml
> +    pipelinesascode.tekton.dev/on-target-branch: "[pipelines-svc-0.1-6e05d4d]"
```suggestion
    pipelinesascode.tekton.dev/on-target-branch: "[pipeline-svc-0.1-f2134db]"
```

2022-10-04 10:13 UTC, avinal commented on images/api/Dockerfile
> +FROM registry.access.redhat.com/ubi9/go-toolset:1.17 as builder
We must upgrade to go 1.18 or our CI is almost useless. In PR #10 you have added 
https://github.com/openshift-pipelines/tektoncd-results/pull/10/files#diff-e3e3626323997573b9caec04c0895ba573f528b38f590d8f1fafd02c2b4bc5afR2 this image. We will have to see if this works now

2022-10-04 17:57 UTC, adambkaplan commented on .tekton/tekton-results-api-pull-request.yaml
> +    pipelinesascode.tekton.dev/on-target-branch: "[pipelines-svc-0.1-6e05d4d]"
done!

2022-10-04 17:58 UTC, adambkaplan commented on images/api/Dockerfile
> +FROM registry.access.redhat.com/ubi9/go-toolset:1.17 as builder
I've upgraded to use the 1.18 image. I also missed the copying of the vendor directory. Upstream results now uses vendored code, so we should not have `go mod download` instructions.

2022-10-04 20:03 UTC, avinal commented on images/api/Dockerfile
> +
```suggestion
```
Remove this line in favor of vendor

2022-10-04 20:03 UTC, avinal commented on images/watcher/Dockerfile
> +
```suggestion
```

2022-10-04 20:03 UTC, avinal commented on images/api/Dockerfile
> +FROM registry.access.redhat.com/ubi9/go-toolset:1.17 as builder
Yes, You forgot to remove the lines IG.

2022-10-07 14:58 UTC, adambkaplan commented
Merging this PR in the interim - our CI cluster is down for a bit.

2022-10-07 14:58 UTC, merged