make tekton results watcher kcp aware
openshift-pipelines/tektoncd-results-for-konflux pull request #17
Opened 2022-11-07 16:46 UTC by avinal

- using kcp version 0.9.0
- upgrade dependencies
- fix pod template not found bug in tektoncd/cli
- add kcp-aware watcher mechanism

Signed-off-by: Avinal Kumar <avinal@redhat.com>
Co-authored-by: Sayan Biswas <sbiswas@redhat.com>

2022-11-07 16:54 UTC, avinal commented
@adambkaplan @sayan-biswas PTAL

2022-11-09 14:58 UTC, adambkaplan requested changes
The KCP changes here look good. I would revert the changes that are not KCP-related, and submit those as separate pull requests to upstream Tekton Results.

2022-11-09 14:58 UTC, adambkaplan commented on cmd/watcher/main.go
>  		} else {
Per our conversation - these changes are fixes to deprecated methods. I would revert these changes and put them in a separate pull request that we send to upstream Tekton Results.

2022-11-09 14:58 UTC, adambkaplan commented on go.mod
> +	github.com/tektoncd/pipeline v0.40.2
I would avoid updating tektoncd dependencies unless we really need it. This too should be done in a separate upstream pull request.

2022-11-10 08:25 UTC, sayan-biswas approved these changes
LGTM

2022-11-10 12:22 UTC, avinal commented on cmd/watcher/main.go
>  		} else {
Done

2022-11-10 12:22 UTC, avinal commented on go.mod
> +	github.com/tektoncd/pipeline v0.40.2
done

2022-11-10 13:54 UTC, gabemontero commented
per the conversation we had this morning, should we adjust the PR title here @avinal @sayan-biswas ... technically, this is not making results "kcp aware"

2022-11-11 20:23 UTC, adambkaplan approved these changes
/approve

2022-11-11 20:23 UTC, merged