Add database column type migrator
openshift-pipelines/tektoncd-results-for-konflux pull request #40
Opened 2023-04-12 06:08 UTC by sayan-biswas

Add custom migrator to match column types to GORM model.

2023-04-12 10:59 UTC, Roming22 commented on .tekton/tekton-results-migrator-push.yaml
> +# Triggers Tekton Results migrator image build on pull request
`push`

2023-04-12 10:59 UTC, Roming22 commented on images/migrator/Dockerfile
> +# Docker configuration to build Tekton Results apiserver image
`apiserver` -> `migrator`

2023-04-12 10:59 UTC, Roming22 commented on tools/type-migrator/migrator.go
> +			fileType := clause.Expr{SQL: m.DataTypeOf(field)}
`fileType` -> `fieldType`?

2023-04-12 13:18 UTC, gabemontero reviewed
in addition to the logging you have in main, I think some logging to indicate whether changes were needed or not would be helpful @sayan-biswas 

I see some logs in the deep innards of the alter path, but it feels like some sort of changes were not needed indicator would be good IMO

2023-04-12 15:08 UTC, adambkaplan requested changes
/approve

General approval, but not quite ready to merge. A few things that must be fixed:

1. Use the UBI9 image for golang
2. Add the signal handler so the migrator doesn't exit, since we are running this in a Deployment instead of a Job
3. Bring the migrator into the `base` kustomization directory.

2023-04-12 15:08 UTC, adambkaplan commented on images/migrator/Dockerfile
> +FROM registry.ci.openshift.org/openshift/release:golang-1.18 AS builder
We have an official RHEL image for golang 1.18 - use that instead:

```suggestion
FROM registry.access.redhat.com/ubi9/go-toolset:1.18 AS builder
```

2023-04-12 15:08 UTC, adambkaplan commented on tools/migrator/migrator.go
> +		}
Why is dry run set to false here?

2023-04-12 15:08 UTC, adambkaplan commented on tools/migrator/migrator.go
> +		} else {
Is most of this logic coming from gorm source? If so, please add a comment indicating that this was inspired by gorm's auto migrator.

2023-04-12 15:08 UTC, adambkaplan commented on tools/migrator/migrator.go
> +					}
Note - also worth adding a comment here about bytea conversion.

2023-04-12 15:08 UTC, adambkaplan commented on config/components/migrator/kustomization.yaml
> +patchesStrategicMerge:
Two items:

1. Recommend using `resources:`, not `patchesStrategicMerge`

   ```suggestion
   resources:
   ```
2. Since this is effectively a hot fix, I would just put the migrator deployment in the "base" directory and include it in the base `kustomization.yaml` as a resource. This will make the deploy in Pipeline Service easier. We can worry about components/etc if/when we upstream this.

2023-04-12 15:08 UTC, adambkaplan commented on tools/migrator/main.go
> +	log.Println("Migration completed!!")
Unfortunately this will crashloop, since main exits :(.

Easy work around - add a signal handler that waits for SIGINT/SIGTERM. This way the binary won't exit until Kubernetes does it for us. See https://gobyexample.com/signals for a good example.

2023-04-12 18:45 UTC, sayan-biswas commented on tools/migrator/migrator.go
> +		}
The `DryRun` prevents execution of the SQL statement built by the ORM. Here we are using two separate DB session, one for querying and one for the transactions.  So, if the `DryRun` flag is set `true` in the global GORM config the transaction session should not execute the SQLs, but the query session still needs to execute SQL, because it executes SQL for fetching information about the tables and the columns.

2023-04-12 21:07 UTC, sayan-biswas commented on images/migrator/Dockerfile
> +FROM registry.ci.openshift.org/openshift/release:golang-1.18 AS builder
Done

2023-04-12 21:11 UTC, sayan-biswas commented on config/components/migrator/kustomization.yaml
> +patchesStrategicMerge:
I have moved the `migrator.yaml` to base . But I did not understand why it should not be a `patchStrategicMerge`. After all the migrator is not a separate deployment, it is to be include in the API deployment as an init container, right?

2023-04-12 21:17 UTC, sayan-biswas commented on tools/migrator/main.go
> +	log.Println("Migration completed!!")
My understanding is that, if the `main` exits successfully then the init container pod completes its lifecycle and the deployment progresses with creating the container pods. If w are waiting for system interrupts, then when does the pod completes?

2023-04-12 21:28 UTC, sayan-biswas commented
> in addition to the logging you have in main, I think some logging to indicate whether changes were needed or not would be helpful @sayan-biswas
> 
> I see some logs in the deep innards of the alter path, but it feels like some sort of changes were not needed indicator would be good IMO

@gabemontero I have added logs which display when column are skipped, or changes were not required. 
This migrator code actually needs a lot more definition, but since this is only to fix the schema, so I left it like that. The idea is to build a fully functional migrator in upstream and get it to downstream.

2023-04-13 13:16 UTC, adambkaplan commented on config/components/migrator/kustomization.yaml
> +patchesStrategicMerge:
My bad on the strategic merge - I misread the file and thought this referenced a separate Deployment. In which case, the container is expected to exit (disregard my comment below).

2023-04-13 13:16 UTC, adambkaplan commented on tools/migrator/main.go
> +	log.Println("Migration completed!!")
Disregard my comment, as you are right this is running in an init container.

2023-04-13 13:27 UTC, adambkaplan approved these changes
LGTM, but not merging until we have the quay.io repo for the migrator image.

2023-04-13 13:27 UTC, adambkaplan commented on .tekton/tekton-results-migrator-push.yaml
> +      value: "quay.io/redhat-appstudio/tekton-results-migrator:{{revision}}"
/hold

Need to wait for this repository to be provisioned.

2023-04-13 14:21 UTC, merged