Add downstream management doc
openshift-pipelines/tektoncd-results-for-konflux pull request #41
Opened 2023-04-19 13:40 UTC by enarha

We created new process for managing our fork and the document describes the process and the specific steps to follow.

2023-04-19 13:56 UTC, avinal requested changes

2023-04-19 13:56 UTC, avinal commented on downstream.md
> +1. Sync the upstream branch: `git checkout main && git pull upstream main`. If new changes are brought from upstream, make sure they are merged using the `Fast-forward` mechanism and no merge commit
```suggestion
1. Sync the upstream branch: `git checkout main && git pull --ff-only upstream main`. If new changes are brought from upstream, make sure they are merged using the `Fast-forward` mechanism and no merge commit was created.
```
Making the command explicit. We can also use `git fetch upstream && git rebase upstream/main`. Since we are updating the upstream branch with upstream only changes. It should always resolve itself.

2023-04-19 13:56 UTC, avinal commented on downstream.md
> +5. Rebase the main branch: `git rebase main`
We should mention somewhere that the downstream `main` branch is a mirror of the upstream main branch.

2023-04-19 13:56 UTC, avinal commented on downstream.md
> +
We should have a step to push to the main too. It will keep our mirror in sync.

2023-04-19 16:08 UTC, enarha commented on downstream.md
> +5. Rebase the main branch: `git rebase main`
Covered that in 9).

2023-04-19 16:08 UTC, enarha commented on downstream.md
> +
Done.

2023-04-19 16:08 UTC, enarha commented on downstream.md
> +1. Sync the upstream branch: `git checkout main && git pull upstream main`. If new changes are brought from upstream, make sure they are merged using the `Fast-forward` mechanism and no merge commit
sure.

2023-04-20 07:52 UTC, sayan-biswas approved these changes

2023-04-20 10:32 UTC, avinal approved these changes
Seems good to me

2023-04-20 12:32 UTC, merged