DO NOT MERGE, CI ONLY Downstream 0.5.0 03
openshift-pipelines/tektoncd-results-for-konflux pull request #43
Opened 2023-05-15 07:29 UTC by avinal

- Allow users/integrators to pass arbitrary keys/values through Result and RecordSummary annotations.
- Fix version tag for results release
- Update kustomization files to latest standard
- Bump gorm.io/gorm from 1.24.3 to 1.25.0
- Bump go version to 1.19
- Make e2e tests more configurable
- Bump google.golang.org/grpc from 1.53.0 to 1.55.0
- Bump k8s.io/api from 0.25.8 to 0.25.9
- [CARRY]: Tekton Results downstream configuration

2023-05-15 07:37 UTC, avinal commented
cc @prietyc123

2023-05-15 08:33 UTC, prietyc123 commented on .tekton/tekton-results-api-push.yaml
> +# Triggers Tekton Results api image build on pull request
```suggestion
# Triggers Tekton Results api image build on push request
```

2023-05-15 08:47 UTC, prietyc123 commented on downstream.md
> +    2. In the description add and properly update the following fields:
```suggestion
    2. In the description add and properly update the following fields:
```
Could you please elaborate this line more.

2023-05-15 08:55 UTC, prietyc123 requested changes
Minor changes requested.

2023-05-15 15:11 UTC, avinal commented
Will create another PR in favor of 0.6.0, closing this.

2023-05-15 15:11 UTC, closed without merging

2023-05-16 10:07 UTC, enarha commented on downstream.md
> +    2. In the description add and properly update the following fields:
@prietyc123 when creating the PR for testing the mix of upstream + downstream changes, we edit the PR description and add the fields (lines) listed below, this is what "add" stands for. We also "update" them to reflect on the upstream changes included in the PR, specifically which ones are new features (if any), changes which require updates in the deployment configuration and breaking changes.