Add Tekton Result build configuration for HACBS
openshift-pipelines/tektoncd-results-for-konflux pull request #5
Opened 2022-08-23 09:57 UTC by avinal

## Changes
- Build Tekton Results components in 
- Add build PipelineRun push and pull request configurations for api and watcher 
- Pull request to add Tekton Results build config to infra-deployments: redhat-appstudio/infra-deployments#605
- Jira issue: PLNSRVCE-548

Signed-off-by: Avinal Kumar <avinal@redhat.com>

2022-08-24 19:03 UTC, adambkaplan requested changes
I would not put our Dockerfiles in `cmd`, since this is a go package. Most developers prefer to keep go packages free of other files (Markdown READMEs perhaps the exception).

I would move this to a separate directory, such as `images`, where Dockerfiles are stored.

Example:

- `images/api/Dockerfile`
- `images/watcher/Dockerfile`

This may impact the `path-context` parameter that you are setting in the HACBS pipeline. I'm not 100% sure on what this does. If this sets the context directory for buildah, then you probably want to omit it because the image build will need all go code from the source root.

2022-08-24 19:03 UTC, adambkaplan commented on .tekton/tekton-results-watcher-push.yaml
> +    - name: path-context
What does `path-context` do here? Is this a context directory for a buildah build?

2022-08-24 19:03 UTC, adambkaplan commented on .tekton/tekton-results-watcher-pull-request.yaml
> +    - name: path-context
Similar - what does `path-context` do here?

2022-08-25 09:51 UTC, avinal commented on .tekton/tekton-results-watcher-push.yaml
> +    - name: path-context
It seems so, by default it is set to project root. Couldn't find any documentation describing this param but seeing the examples from jvm-build it should point to the base directory for all the code. Code: https://github.com/redhat-appstudio/build-service/blob/ce5cecf8c5e5bad1c66aafae8222341bbe82a22a/controllers/component_build_controller.go#L603, I will omit this.

2022-08-26 12:26 UTC, adambkaplan approved these changes
Looks good! Is there any way we can verify the HACBS build succeeds prior to merge?

2022-08-26 12:33 UTC, avinal commented
> Looks good! Is there any way we can verify the HACBS build succeeds prior to merge?

It is kind of a deadlock, configurations are needed in both tektoncd-results and infra-deployments to enable image building. Also, we need to [install the PaC CI App](https://github.com/redhat-appstudio/infra-deployments#component-testing-and-building-of-images) in our repo. I have raised a request, please check.

2022-08-26 12:41 UTC, adambkaplan commented
I'll merge this then - if we need to fix anything we can do so in a follow-up PR.

2022-08-26 12:41 UTC, merged