temp fix to unmarshalling error in recordSummaryAnnotations
openshift-pipelines/tektoncd-results-for-konflux pull request #63
Opened 2024-03-04 18:18 UTC by ramessesii2

- related to PLNSRVCE-1679

Signed-off-by: Satyam Bhardwaj <sabhardw@redhat.com>

rh-pre-commit.version: 2.2.0
rh-pre-commit.check-secrets: ENABLED

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you review them:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] [Tested your changes locally](https://github.com/tektoncd/results/blob/main/docs/DEVELOPMENT.md) (if this is a code change)
- [ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [ ] Has a kind label. You can add a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user-facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contain the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

2024-03-04 19:47 UTC, gabemontero requested changes
I don't see how this fixes the error @ramessesii2 

you are still returning an error that is bubbled up to the caller regardless 
and while knative controller will ignore it i.e. what I see in vendor/knative.dev/pkg/controller/controller.go, you still bypass all the subsequent processing that we want to do

@sayan-biswas @avinal would you all agree, or what am I missing

2024-03-04 19:47 UTC, gabemontero commented on pkg/watcher/results/results.go
>  			if err != nil {
don't you want to check for PermanentError here and ignore it

2024-03-05 11:53 UTC, ramessesii2 commented on pkg/watcher/results/results.go
>  			if err != nil {
I'm not sure why originally the error is not subdued. A little bit of low level detail though - this recordSummaryAnnotaion is a key in the RESULTS table in the database, so every entry/row has this `recordsummary_annotations` filed with the value same as the value of "results.tekton.dev/recordSummaryAnnotations".

So, I'm happy to make that change if it's not critical to the operation of the function. I'm gonna tag @sayan-biswas if he can share any insights.

2024-03-05 12:01 UTC, ramessesii2 commented
> I don't see how this fixes the error 

@gabemontero I've tried addressing this particular error in logs `error parsing annotation results.tekton.dev/recordSummaryAnnotations: json: cannot unmarshal number into Go value of type string`, this is it's [source from PaC](https://github.com/openshift-pipelines/pipelines-as-code/blob/main/pkg/kubeinteraction/resultsannotation.go#L15), the 
`pull_request-id` is an int, results assumes a map[string]string. So, in this temp fix, I've basically done type conversion using `any` (just looked online, it's suggested to use interface{} instead). 
Does that make sense?

2024-03-05 13:05 UTC, gabemontero commented
> > I don't see how this fixes the error
> 
> @gabemontero I've tried addressing this particular error in logs `error parsing annotation results.tekton.dev/recordSummaryAnnotations: json: cannot unmarshal number into Go value of type string`, this is it's [source from PaC](https://github.com/openshift-pipelines/pipelines-as-code/blob/main/pkg/kubeinteraction/resultsannotation.go#L15), the `pull_request-id` is an int, results expects a map[string]string. So, in this temp fix, I've basically done type conversion, first unmarshalling into `map[string]any` (just looked online, it's suggested to use interface{} instead) and then to the format Results expect. Does that make sense?

OK so you are trying to fix this, not just ignore the error.  I did not pick up on that before.

From what I hear in the slack thread, this is needs to be a permanent solution, and not a temp fix.  That there is not a change needed on the PAC side.

I know we cannot make PAC a dependency, but I'm almost inclined to just duplicate the `ResultAnnotation` struct declaration in Results and just map to that.

Let's get a PR upstream going as well, pull in @sayan-biswas @khrm etc. and sort this out.  The see about temporarily duplicating in this PR short term if it is taking too long to get the upstream fix.

2024-03-05 13:48 UTC, ramessesii2 commented
Closing it in favor of https://github.com/tektoncd/results/pull/722

2024-03-05 13:48 UTC, closed without merging